parameters:
#    site_gallery.example.class: Site\GalleryBundle\Example
    img_host: http://images.nfsko.dev/gallery/
    img_dir: ../../images.nfsko.dev/www/gallery/
    gallery_service.class: Site\GalleryBundle\GalleryService
    redirect_service.class: Site\GalleryBundle\RedirectService
    # Коэффициенты для расчёта доступного диского пространства в галерее
    posts_min: 10 # Минимальное число тематических сообщений
    posts_inc: 250 # Инкремент тематических сообщений
    kb_inc: 750 # Инкремент Кб за каждые posts_inc тематических сообщений

services:
#    site_gallery.example:
#        class: %site_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    gallery_redirect_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [redirect]
        calls:
            - [pushHandler, [@gallery_redirect_handler]]
    gallery_redirect_handler:
        class: Monolog\Handler\StreamHandler
        # 200 = INFO, see Monolog::Logger for the values of log levels
        arguments: [%kernel.root_dir%/logs/gallery_redirect.log, 200]        
    gallery_add_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [add]
        calls:
            - [pushHandler, [@gallery_manage_handler]]
    gallery_edit_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [edit]
        calls:
            - [pushHandler, [@gallery_manage_handler]]
    gallery_remove_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [remove]
        calls:
            - [pushHandler, [@gallery_manage_handler]]
    gallery_manage_handler:
        class: Monolog\Handler\StreamHandler
        # 200 = INFO, see Monolog::Logger for the values of log levels
        arguments: [%kernel.root_dir%/logs/gallery_manage.log, 200]
    
    gallery_service:
        class: "%gallery_service.class%"
        arguments: [@doctrine.orm.entity_manager, @gallery_add_logger, @security.context, @validator, %img_host%, %posts_min%, %posts_inc%, %kb_inc%]
    redirect_service:
        class: "%redirect_service.class%"
        arguments: [@service_container, @gallery_redirect_logger]